/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/gigs": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": (components["schemas"]["GigDto"])[];
            "application/json": (components["schemas"]["GigDto"])[];
            "text/json": (components["schemas"]["GigDto"])[];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateGigDto"];
          "text/json": components["schemas"]["CreateGigDto"];
          "application/*+json": components["schemas"]["CreateGigDto"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["GigDto"];
            "application/json": components["schemas"]["GigDto"];
            "text/json": components["schemas"]["GigDto"];
          };
        };
      };
    };
    delete: {
      parameters: {
        query?: {
          id?: string;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/gigs/{id}/signup": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
  "/whoami": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": string;
            "application/json": string;
            "text/json": string;
          };
        };
      };
    };
  };
  "/logout": {
    post: {
      responses: {
        /** @description Success */
        200: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateGigDto: {
      type: string;
      /** Format: date-time */
      start: string;
      /** Format: date-time */
      end: string;
      address: string;
      /** Format: int32 */
      maxWorkers: number;
    };
    GigDto: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      start: string;
      /** Format: date-time */
      end: string;
      address: string;
      /** Format: int32 */
      maxWorkers: number;
      workerIds: (string)[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
