version: '3'
services:
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ordo
      - POSTGRES_PASSWORD=ordo
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 5433:8080
